### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by jg8481it** [s4int/robotframework-KafkaLibrary#2]
Will this work with Python 3?

**Comment by s4int** [comment]
I've not tested it with Python 3.
You can test it with Python 3, if it's not working I'll fix it.

**Comment by jg8481it** [comment]
Hi, thanks for the reply. I was actually able to figure it out. I ran the `2to3` tool on all of the KafkaLibrary files. After converting them I was able run this in Python 3.

Thanks again I'm closing this issue, and excellent work with this library. Works really well!
