### ISSUE TITLE
outdated git repository

### ISSUE THREAD

**Issue by tsaboto** [s4int/robotframework-KafkaLibrary#4]
Hello how are you? 

I'm trying to install your library "https://github.com/s4int/robotframework-KafkaLibrary" to use in Robotframework with Python 3.5, but in the pip / pip3 repository
according to your GIT repository.

https://pypi.org/simple/robotframework-kafkalibrary/

Are you interested in updating?

Appreciate.

Tatiane Saboto

**Comment by tsaboto** [comment]
#Python2 
#!/usr/bin/env python

from os.path import join, dirname
from setuptools import setup

execfile(join(dirname(__file__), 'KafkaLibrary', 'version.py'))

DESCRIPTION = """
Kafka support for Robot Framework.
"""[1:-1]

#Python3 

#!/usr/bin/env python

from os.path import join, dirname
from setuptools import setup

filename=join(dirname(__file__), 'KafkaLibrary', 'version.py')
exec(compile(open(filename).read(),filename, 'exec'))

DESCRIPTION = """

**Comment by s4int** [comment]
Thank you.
I've fixed that issue and will release new version with that and couple other fixes.

**Comment by s4int** [comment]
Fixed in #10
