### ISSUE TITLE
cannot install in Python 3.6.8

### ISSUE THREAD

**Issue by Reefay** [s4int/robotframework-KafkaLibrary#8]
setup.py line 6 execfile is failing on a pip install. It appears the code is correct in the github (exec), but the setup.py on pypi is incorrect (execfile).

**Comment by Reefay** [comment]
Along with this, your __init__.py from PyPi is wrong as well. The one on github works

**Comment by s4int** [comment]
Thank you.

I will release new version with fixes.

**Comment by s4int** [comment]
It is fixed with version 0.0.3. #10 
Please update with:
`pip install -U robotframework-kafkalibrary`

**Comment by s4int** [comment]
Fixed in #10
